CREATE TABLE public.pets
(
    pet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text,
    birth_date timestamp without time zone,
    PRIMARY KEY (pet_id)
);

ALTER TABLE public.pets
    OWNER to eyet;

CREATE TABLE public.customer
(
    customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text,
    PRIMARY KEY (customer_id)
);

CREATE TABLE public.address
(
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address_line text,
    customer_id integer
    PRIMARY KEY (address_id)
);


